package org.software.open.source.vietnamese.provinces.service.io.repositories;

import org.software.open.source.vietnamese.provinces.service.io.entities.AdministrativeUnitsEntity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

/**
 * Repository interface for AdministrativeUnitsEntity
 * Generated by 04-entity-to-repository.sh
 */
public interface AdministrativeUnitsRepository extends JpaRepository<AdministrativeUnitsEntity, Integer> {

  @Query(value = """
      SELECT e
      FROM AdministrativeUnitsEntity e
      WHERE LOWER(e.fullName) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.fullNameEn) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.shortName) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.shortNameEn) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.codeName) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.codeNameEn) LIKE CONCAT('%', LOWER(:search), '%')
      """, countQuery = """
      SELECT COUNT(e)
      FROM AdministrativeUnitsEntity e
      WHERE LOWER(e.fullName) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.fullNameEn) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.shortName) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.shortNameEn) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.codeName) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.codeNameEn) LIKE CONCAT('%', LOWER(:search), '%')
      """)
  Page<AdministrativeUnitsEntity> searchAdministrativeUnits(String search, Pageable pageable);

}
