package org.software.open.source.vietnamese.provinces.service.io.repositories;

import org.software.open.source.vietnamese.provinces.service.io.entities.AdministrativeRegionsEntity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

/**
 * Repository interface for AdministrativeRegionsEntity
 * Generated by 04-entity-to-repository.sh
 */
public interface AdministrativeRegionsRepository extends JpaRepository<AdministrativeRegionsEntity, Integer> {
  @Query(value = """
      SELECT e
      FROM AdministrativeRegionsEntity e
      WHERE LOWER(e.name) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.nameEn) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.codeName) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.codeNameEn) LIKE CONCAT('%', LOWER(:search), '%')
      """, countQuery = """
      SELECT COUNT(e)
      FROM AdministrativeRegionsEntity e
      WHERE LOWER(e.name) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.nameEn) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.codeName) LIKE CONCAT('%', LOWER(:search), '%')
         OR LOWER(e.codeNameEn) LIKE CONCAT('%', LOWER(:search), '%')
      """)
  Page<AdministrativeRegionsEntity> searchAdministrativeRegions(
      @Param("search") String search,
      Pageable pageable);
}
