package org.software.open.source.vietnamese.provinces.service.io.repositories;

import org.software.open.source.vietnamese.provinces.service.io.entities.ProvincesEntity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

/**
 * Repository interface for ProvincesEntity
 * Generated by 04-entity-to-repository.sh
 */
public interface ProvincesRepository extends JpaRepository<ProvincesEntity, String> {

  @Query("SELECT p FROM ProvincesEntity p WHERE " +
      "LOWER(p.name) LIKE LOWER(CONCAT('%', :search, '%')) OR " +
      "LOWER(p.nameEn) LIKE LOWER(CONCAT('%', :search, '%')) OR " +
      "LOWER(p.codeName) LIKE LOWER(CONCAT('%', :search, '%'))")
  Page<ProvincesEntity> searchProvinces(@Param("search") String search, Pageable pageable);

}
