package org.software.open.source.vietnamese.provinces.service.io.repositories;

import java.util.List;

import org.software.open.source.vietnamese.provinces.service.io.entities.WardsEntity;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Repository interface for WardsEntity
 * Generated by 04-entity-to-repository.sh
 */
public interface WardsRepository extends JpaRepository<WardsEntity, String> {

  List<WardsEntity> findByProvinceCodeIn(List<String> provinceCodes);
}
