package org.software.open.source.vietnamese.provinces.service.service;

import org.software.open.source.vietnamese.provinces.service.entries.apis.models.responses.AdministrativeRegionsResponse;
import org.software.open.source.vietnamese.provinces.service.entries.apis.models.responses.PageResponse;

/**
 * Service interface for AdministrativeRegionsEntity
 * Generated by 05-entity-to-service.sh
 */
public interface AdministrativeRegionsService {

  PageResponse<AdministrativeRegionsResponse> getAdministrativeRegions(String search, int page, int size,
      String sortBy, String sortDir);
}
