package org.software.open.source.vietnamese.provinces.service.service;

import org.software.open.source.vietnamese.provinces.service.entries.apis.models.responses.AdministrativeUnitsResponse;
import org.software.open.source.vietnamese.provinces.service.entries.apis.models.responses.PageResponse;

/**
 * Service interface for AdministrativeUnitsEntity
 * Generated by 05-entity-to-service.sh
 */
public interface AdministrativeUnitsService {

  PageResponse<AdministrativeUnitsResponse> getAdministrativeUnits(String search,
      int page, int size, String sortBy,
      String sortDir);
}
