package org.software.open.source.vietnamese.provinces.service.service;

import org.software.open.source.vietnamese.provinces.service.entries.apis.models.responses.PageResponse;
import org.software.open.source.vietnamese.provinces.service.entries.apis.models.responses.ProvincesResponse;

/**
 * Service interface for ProvincesEntity
 * Generated by 05-entity-to-service.sh
 */
public interface ProvincesService {

  PageResponse<ProvincesResponse> getProvinces(String search,
      int page, int validSize, String sortBy,
      String sortDir, boolean includeWard);
}
